sync_top:
  every: 300s
  class: CryptoSyncTop
  args:
  queue: crypto
  description: Runs the perform method in CryptoSyncTop

sync_all:
  every: 1800s
  class: CryptoSyncAll
  args:
  queue: crypto
  description: Runs the perform method in CryptoSyncAll

sync_all:
  every: 1800s
  class: CryptoAlertSendAll
  args:
  queue: crypto
  description: Runs the perform method in CryptoAlertSendAll
